/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v7.0
processor: MIMXRT1062xxxxA
package_id: MIMXRT1062DVL6A
mcu_data: ksdk2_0
processor_version: 7.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: f97233eb-8e44-45df-9ba5-345de1b5ecb6
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * FLEXIO3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXIO3'
- type: 'flexio_mculcd'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'flexio_mculcd_71c03477918e9bdca54eff5edc785168'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXIO3'
- config_sets:
  - fsl_flexio_mculcd:
    - clockSource: 'FlexIoClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - peripheralConfig:
      - busType: 'kFLEXIO_MCULCD_8080'
      - dataFlexIOMcuLcdBusWidth: '8'
      - dataPinStartIndex: '0'
      - ENWRPinIndex: '8'
      - RDPinIndex_sel: '12'
      - setCSPinStruct:
        - function_type: 'functionDN'
        - gpio_peripherals: 'GPIO2'
        - gpio_signals: 'gpio_io.01'
        - disableGPIOCheck: 'false'
      - setRSPinStruct:
        - function_type: 'functionDN'
        - gpio_peripherals: 'GPIO2'
        - gpio_signals: 'gpio_io.00'
        - disableGPIOCheck: 'false'
      - txShifterEndIndex: '3'
      - rxShifterStartIndex: '3'
    - config:
      - enable: 'true'
      - enableInDoze: 'false'
      - enableInDebug: 'false'
      - enableFastAccess: 'false'
      - baudRate_Bps: '320000000'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* FlexIO peripheral configuration */
FLEXIO_MCULCD_Type FLEXIO3_peripheralConfig = {
  .flexioBase = FLEXIO3_PERIPHERAL,
  .busType = kFLEXIO_MCULCD_8080,
  .dataPinStartIndex = 0,
  .ENWRPinIndex = 8,
  .RDPinIndex = 12,
  .setRDWRPin = NULL,
  .setCSPin = FLEXIO3_setCSPin,
  .setRSPin = FLEXIO3_setRSPin,
  .txShifterStartIndex = 0,
  .txShifterEndIndex = 3,
  .rxShifterStartIndex = 3,
  .rxShifterEndIndex = 3,
  .timerIndex = 0
};
/* FlexIO MCULCD configuration */
flexio_mculcd_config_t FLEXIO3_config = {
  .enable = true,
  .enableInDoze = false,
  .enableInDebug = false,
  .enableFastAccess = false,
  .baudRate_Bps = 320000000
};

/* GPIO CS pin set function */
void FLEXIO3_setCSPin(bool set){
  GPIO_PinWrite(FLEXIO3_GPIO_PERIPHERAL_CSPIN, FLEXIO3_GPIO_CSPIN, (uint8_t)set);
}

/* GPIO RS pin set function */
void FLEXIO3_setRSPin(bool set){
  GPIO_PinWrite(FLEXIO3_GPIO_PERIPHERAL_RSPIN, FLEXIO3_GPIO_RSPIN, (uint8_t)set);
}

void FLEXIO3_init(void) {
  /* Master initialization */
  FLEXIO_MCULCD_Init(&FLEXIO3_peripheralConfig, &FLEXIO3_config, FLEXIO3_CLK_FREQ);
}

/***********************************************************************************************************************
 * ADC2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC2'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_6a490e886349a7b2b07bed10ce7b299b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC2'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver2'
      - samplePeriodMode: 'kADC_SamplePeriodShort2Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount8'
      - enableHardwareTrigger: 'software'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'false'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC2_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.3'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 1:
        - channelNumber: 'IN.2'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC2_config = {
  .enableOverWrite = false,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort2Clocks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver2,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC2_channels_config[2] = {
  {
    .channelNumber = 3U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 2U,
    .enableInterruptOnConversionCompleted = false
  }
};
void ADC2_init(void) {
  /* Initialize ADC2 peripheral. */
  ADC_Init(ADC2_PERIPHERAL, &ADC2_config);
  /* Configure ADC2 peripheral to average 8 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC2_PERIPHERAL, kADC_HardwareAverageCount8);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  FLEXIO3_init();
  ADC2_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
