/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_adc.h"
#include "fsl_flexio_mculcd.h"
#include "fsl_gpio.h"
#include "fsl_pwm.h"
#include "fsl_sai.h"
#include "fsl_sai_edma.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA0_DMAMUX_BASEADDR DMAMUX
/* BOARD_InitPeripherals defines for ADC2 */
/* Definition of peripheral ID */
#define ADC2_PERIPHERAL ADC2
/* Definition of special channel interconnected with ADC_ETC which takes real channel to be measured from ADC_ETC. */
#define ADC2_CHANNEL_DRIVEN_BY_ADC_ETC 16U
/* Definition of peripheral ID */
#define FLEXIO3_PERIPHERAL FLEXIO3
/* Definition of the clock source frequency */
#define FLEXIO3_CLK_FREQ 120000000UL
/* FlexIO MCULCD data bus width check */
#if ((defined(FLEXIO_MCULCD_DATA_BUS_WIDTH) && (FLEXIO_MCULCD_DATA_BUS_WIDTH != 8)))
  #error FLEXIO_MCULCD_DATA_BUS_WIDTH define value is not the same as value in the Data bus width setting in the FLEXIO3 component instance. Check define (missing or different value) at the project setting.
#endif
/* GPIO CS pin peripheral */
#define FLEXIO3_GPIO_PERIPHERAL_CSPIN GPIO2
/* GPIO CS pin number */
#define FLEXIO3_GPIO_CSPIN 1UL
/* GPIO RS pin peripheral */
#define FLEXIO3_GPIO_PERIPHERAL_RSPIN GPIO2
/* GPIO RS pin number */
#define FLEXIO3_GPIO_RSPIN 0UL
/* Definition of peripheral ID */
#define PWM1_PERIPHERAL PWM1
/* Definition of submodule 3 ID */
#define PWM1_SM0 kPWM_Module_3
/* Definition of submodule 3 counter (PWM) desired frequency in Hertz */
#define PWM1_SM0_COUNTER_FREQ_HZ 50000U
/* Definition of submodule 3 counter clock source frequency in Hertz */
#define PWM1_SM0_COUNTER_CLK_SOURCE_FREQ_HZ 150000000U
/* Definition of submodule 3 channel A ID */
#define PWM1_SM0_A kPWM_PwmA
/* Definition of submodule 3 channel B ID */
#define PWM1_SM0_B kPWM_PwmB
/* Definition of submodule 3 channel X ID */
#define PWM1_SM0_X kPWM_PwmX
/* Definition of fault Fault0 ID */
#define PWM1_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define PWM1_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define PWM1_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define PWM1_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define SAI1_PERIPHERAL SAI1
/* Bit clock source frequency used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_BCLK_SOURCE_CLOCK_HZ 150000000UL
/* Sample rate used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_SAMPLE_RATE 16000UL
/* Word width used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_WORD_WIDTH 16U
/* Number of words within frame used for calculating the bit clock divider in the TxSetBitClockRate function. */
#define SAI1_TX_WORDS_PER_FRAME 2U
/* SAI1 eDMA source request. */
#define SAI1_TX_DMA_REQUEST kDmaRequestMuxSai1Tx
/* Selected eDMA channel number. */
#define SAI1_TX_DMA_CHANNEL 0
/* DMAMUX device that is used for muxing of the request. */
#define SAI1_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define SAI1_TX_DMA_BASEADDR DMA0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA0_config;
extern const adc_config_t ADC2_config;
extern const adc_channel_config_t ADC2_channels_config[3];
/* FlexIO peripheral configuration */
extern FLEXIO_MCULCD_Type FLEXIO3_peripheralConfig;
/* FlexIO MCULCD configuration */
extern flexio_mculcd_config_t FLEXIO3_config;
extern pwm_config_t PWM1_SM0_config;

extern pwm_signal_param_t PWM1_SM0_pwm_function_config[1];
extern const pwm_fault_input_filter_param_t PWM1_faultInputFilter_config;
extern const pwm_fault_param_t PWM1_Fault0_fault_config;
extern const pwm_fault_param_t PWM1_Fault1_fault_config;
extern const pwm_fault_param_t PWM1_Fault2_fault_config;
extern const pwm_fault_param_t PWM1_Fault3_fault_config;
extern sai_transceiver_t SAI1_Tx_config;
extern edma_handle_t SAI1_TX_Handle;
extern sai_edma_handle_t SAI1_SAI_Tx_eDMA_Handle;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* GPIO CS pin set function */
void FLEXIO3_setCSPin(bool set);
/* GPIO RS pin set function */
void FLEXIO3_setRSPin(bool set);

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* SAI transfer Tx callback function for the SAI1 component (init. function BOARD_InitPeripherals)*/
extern void i2sCallback(I2S_Type *base, sai_edma_handle_t *handle, status_t status, void *userData);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
